# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e35f0f989f553672f8ea3861b45299f2442809d91e481c866ba475e41b0eec6683241c0d642c678c3ef7d2eea3a8c5028230713d8f847f1013fef6ad1446fad

test:
  secret_key_base: d57ad009b8d56fe62f6c0d7238de480588de03e91fec40ecae2d7ab9ad3cff1e52c3d8b82e394372474aa7a94fec71b85d2187125766309d3a0a76df7b47dbfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
